# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Andrei Rykov"

email: a.g.rykov@glndawur.ru
description: >- # this means to ignore newlines until "baseurl:"
  This is a repo with Personal Website to host on GitHub Pages using Jekyll and Minimal Mistakes
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://glendawur.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  glendawur

# Build settings
# theme: minimal-mistakes-jekyll
markdown: kramdown
minimal_mistakes_skin: "dark"
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

include: 
  - _pages
  - _media

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

author:
  name: "Andrei Rykov"
  avatar: "/assets/images/BIO.png"
  bio: "Research Engineer at Chebyshev Research Center"
  location: "St. Petersburg, Russia"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:a.g.rykov@glndwr.ru"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/glendawur"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/agrykov"
    - label: "Scholar"
      icon: "fa-brands fa-google-scholar"
      url: "https://scholar.google.ru/citations?user=jfJ5E9MAAAAJ&hl=en"
